### ISSUE TITLE
UC02 Manter Usuário

### ISSUE THREAD

**Issue by cantuariavc** [DSW-2018/projetoDesenho#23]
## Descrição

A funcionalidade de manter usuário estabelece as operações de CRUD, ou seja, criação, leitura, atualização e exclusão de dados relacionados ao objeto que representa a classe de usuário. Nesse sentido, ela define que o usuário poderá criar uma conta no sistema e, a partir disto, logar , atualizar as suas informações ou excluir os seus registros.

## Critérios de Aceitação

Diga quais os critérios o sistema deve possuir para que seja enviado o Pull Request.

## Tasks

- [ ] Criar Usuário (Nome, E-mail, senha, Pontos de confiança)
- [ ] Atualizar Usuário
- [ ] Remover Usuário
- [ ] Llstar Usuário

## Checklist

- [x] A issue possui Labels.
- [x] A issue possui nome significativo.

**Comment by cantuariavc** [comment]
Resolvido no PR https://github.com/EconomizAqui/EconomizAqui/pull/39
